
export const SLIDE_DETAILS_REQUEST = 'SLIDE_DETAILS_REQUEST'
export const SLIDE_DETAILS_SUCCESS = 'SLIDE_DETAILS_SUCCESS'
export const SLIDE_DETAILS_FAIL = 'SLIDE_DETAILS_FAIL'
export const SLIDE_DETAILS_RESET = 'SLIDE_DETAILS_RESET'

export const SLIDE_DELETE_REQUEST = 'SLIDE_DELETE_REQUEST'
export const SLIDE_DELETE_SUCCESS = 'SLIDE_DELETE_SUCCESS'
export const SLIDE_DELETE_FAIL = 'SLIDE_DELETE_FAIL'

export const SLIDE_CREATE_REQUEST = 'SLIDE_CREATE_REQUEST'
export const SLIDE_CREATE_SUCCESS = 'SLIDE_CREATE_SUCCESS'
export const SLIDE_CREATE_FAIL = 'SLIDE_CREATE_FAIL'